language: node_js
node_js: "12"
host: 0.0.0.0
port: 3000
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - client/node_modules

script:
  - npm run lint
  - npm run build
  - npm test

